services:
  - type: web
    name: cauldron-optimizer
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: NEONDB_USER
        sync: false
